# Generated by Django 5.2.7 on 2026-03-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_index=True, max_length=255)),
                ('item_url_name', models.CharField(max_length=255, unique=True)),
                ('max_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('item_url_name', models.CharField(max_length=200, verbose_name='URL name предмета')),
                ('target_price', models.FloatField(blank=True, null=True, verbose_name='Целевая цена')),
                ('last_min_price', models.FloatField(blank=True, null=True, verbose_name='Последняя минимальная цена')),
                ('last_avg_price', models.FloatField(blank=True, null=True, verbose_name='Последняя средняя цена')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление')),
                ('min_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item_url_name')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('tracked_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.trackeditem')),
            ],
        ),
    ]
