# Generated by Django 5.2.7 on 2025-10-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('target_price', models.FloatField(blank=True, null=True, verbose_name='Целевая цена')),
                ('last_min_price', models.FloatField(blank=True, null=True, verbose_name='Последняя минимальная цена')),
                ('last_avg_price', models.FloatField(blank=True, null=True, verbose_name='Последняя средняя цена')),
                ('chat_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram chat_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
