# Generated by Django 5.2.7 on 2025-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trackeditem_item_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeditem',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление'),
        ),
    ]
