# Generated by Django 5.2.7 on 2025-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_trackeditem_last_notified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_url_name', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, verbose_name='Telegram chat_id')),
                ('step', models.CharField(default='waiting', max_length=32, verbose_name='Шаг диалога')),
                ('temp_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Временное имя предмета')),
                ('temp_target_price', models.FloatField(blank=True, null=True, verbose_name='Временная целевая цена')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
