# Generated by Django 5.2.7 on 2025-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_marketitem_trackeditemstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitem',
            name='item_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='item_url_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
