# Generated by Django 5.2.7 on 2025-10-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_marketitem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeditem',
            name='max_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackeditem',
            name='min_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
