# Generated by Django 5.2.7 on 2025-11-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_trackeditem_max_rank_trackeditem_min_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='rank_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
