# Generated by Django 5.2.7 on 2025-11-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_marketitem_rank_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketitem',
            old_name='rank_max',
            new_name='max_rank',
        ),
    ]
