# Generated by Django 5.2.7 on 2026-01-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_rank_max_marketitem_max_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Telegram user id', unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Может ли пользователь получать уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
