# Generated by Django 5.2.7 on 2026-01-27 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_telegramprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('telegram_profile', models.ForeignKey(blank=True, help_text='Заполняется после подтверждения через Telegram', null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.telegramprofile')),
            ],
        ),
    ]
