# Generated by Django 5.2.7 on 2026-01-29 13:04

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_telegramauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramauthtoken',
            name='expires_at',
            field=models.DateTimeField(default=tracker.models.telegram_token_expiry),
        ),
        migrations.AddIndex(
            model_name='telegramauthtoken',
            index=models.Index(fields=['token'], name='tracker_tel_token_436f8b_idx'),
        ),
    ]
