# Generated by Django 5.2.7 on 2026-02-12 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_telegramauthtoken_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
