# Generated by Django 5.2.7 on 2026-03-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_trackeditem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackeditem',
            name='chat_id',
        ),
    ]
