# Generated by Django 5.2.7 on 2026-03-11 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_trackeditem_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackeditem',
            unique_together={('user', 'item_url_name')},
        ),
    ]
